config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  delete '/carts', to: "carts#destroy", as: "carts"
  get '/cart', to: "carts#show", as: "cart"
  patch '/cart' => 'carts#update'
  resources :items, only: [:index, :show, :update]
  resources :carts, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :addresses, only: [:new, :create, :edit, :destroy]
  end
  namespace :admin do
    get '/dashboard', to: "orders#dashboard"
    resources :orders, only: [:edit, :update]
    resources :items, only: [:index, :update, :edit]
    resources :users, only: [:show]
  end
  resources :orders, only: [:index, :show, :create]
  resources :charges, only: [:new, :create]
  get '/dashboard', to: "users#show"
  post '/login', to: "sessions#create"
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"
  get '/:category' => 'categories#index'
  patch '/carts/:id' => 'carts#update'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :email, :password, :password_confirmation, presence: true
  validates_uniqueness_of :email
  has_many :orders
  has_many :addresses

  enum role: %w(default admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user] = user.id
      session[:message] = "Logged in as #{user.first_name} #{user.last_name}"
      redirect_to dashboard_path
    else
      flash[:danger] = user.errors.full_messages.first
      redirect_to new_user_path
    end
  end

  def show
    if session[:user]
      @user = User.find(session[:user])
      @addresses = @user.addresses
    else
      redirect_to login_path
    end
  end

  def update
    @user = User.find(session[:user])
    if @user.authenticate(params[:user][:password])
      @user.update(user_params)
      save_user?(@user)
    else
      flash[:danger] = 'Incorrect password'
      redirect_to edit_user_path
    end
  end

  def edit
    @user = User.find(session[:user])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

def save_user?(user)
  if user.save
    flash[:success] = 'Profile successfully updated'
    redirect_to dashboard_path
  else
    flash[:danger] = user.errors.full_messages.first
    redirect_to edit_user_path
  end
end

app/views/users/edit.html.erb
<br/>
<br/>
<br/>
<h1>User's Edit Page</h1>
<%= form_for @user do |f| %>
  <h3>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </h3>

  <h3>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </h3>

  <h3>
  <%= f.label :email  %>
  <%= f.email_field :email %>
  </h3>

  <h3>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </h3>

  <h3>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </h3>

  <h3>
    <%= f.submit %>
  </h3>

<% end %>

app/views/users/new.html.erb
</br></br></br></br>
<div class="jumbotron">
<div class="container">
<h3 class="instructions">Please Enter Your Information:</h3></br>
<div class="form_inline">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label "First name", class:"control-label" %>
      <%= f.text_field :first_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Last name", class: "control-label" %>
      <%= f.text_field :last_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Email", class:"control-label" %>
      <%= f.text_field :email, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Password", class:"control-label" %>
      <%= f.password_field :password, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Password confirmation", class:"control-label" %>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div></br>

    <div class="buttons"><%= f.submit "Create Account", class:"btn btn-primary" %></div>
  </div>
<% end %>
</div></div>

app/views/users/show.html.erb
</br></br></br></br>
<div class="jumbotron">
<div class="container">
<div class="orders">
<h2><%= @user.first_name %> <%= @user.last_name %></h2>
<h4 class="dropper"><%= @user.email %></h4>
<% if @addresses %>
  <h3>Addresses:</h3>
  <% @addresses.each do |address| %>
    <div id="items_button"><%= address.street_address %></br>
    <% if address.secondary_address %>
      <%= address.secondary_address %></br>
    <% end %>
    <%= address.city %>, <%= address.state_abbr %></br>
    <%= address.zip_code %></br>
    <%= button_to "Delete Address", user_address_path(@user, address.id), method: "delete", class: "buttons" %></br>
  <% end %></div>
<% end %>
</br>
<%= button_to "Add an Address", new_user_address_path(@user), method: "get", class: "search_button", class: "buttons" %>
<%= button_to "Edit Your Account", edit_user_path(@user), method: "get", class: "search_button", class: "buttons" %>
</div>