config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  delete '/carts', to: "carts#destroy", as: "carts"
  get '/cart', to: "carts#show", as: "cart"
  patch '/cart' => 'carts#update'
  resources :items, only: [:index, :show, :update]
  resources :carts, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :addresses, only: [:new, :create, :edit, :destroy]
  end
  namespace :admin do
    get '/dashboard', to: "orders#dashboard"
    resources :orders, only: [:edit, :update]
    resources :items, only: [:index, :update, :edit]
    resources :users, only: [:show]
  end
  resources :orders, only: [:index, :show, :create]
  resources :charges, only: [:new, :create]
  get '/dashboard', to: "users#show"
  post '/login', to: "sessions#create"
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"
  get '/:category' => 'categories#index'
  patch '/carts/:id' => 'carts#update'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_items
  has_many :items, through: :order_items

  enum status: %w(ordered paid cancelled completed)

  scope :ordered, -> {where(:status => 0)}
  scope :paid, -> {where(:status => 1)}
  scope :cancelled, -> {where(:status => 2)}
  scope :completed, -> {where(:status => 3)}

  def count
    self.items.count
  end

  def total_price
    self.items.inject(0) do |sum, item|
      sum += item.price
      sum
    end
  end

  def canceled_or_completed
    if self.status == "completed"
      return "Completed at #{self.updated_at}"
    elsif self.status == "cancelled"
      return "Cancelled at #{self.updated_at}"
    end
  end

  def self.make_order(order, items)
    items.each do |item_id, quantity|
      order.add_item(item_id, quantity)
    end
  end

  def add_item(item_id, quantity)
    item = Item.find(item_id.to_i)
    quantity.times do
      self.items << item
    end
  end

  def self.sort(category)
    if category == 'paid'
      @orders = Order.paid
    elsif category == 'cancelled'
      @orders = Order.cancelled
    elsif category == 'completed'
      @orders = Order.completed
    elsif category == 'ordered'
      @orders = Order.ordered
    else
      @orders = Order.all
    end
  end

  def self.status_list
    group(:status).count(:status)
  end

  def update_status(status)
    if status == ""
    else
      update(status: status)
      save
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController


  def dashboard
    @orders = Order.sort(params[:status])
    @status_list = Order.status_list
  end

  def update
    order = Order.find(params[:id])
    order.update_status(params[:update_status])
    redirect_to admin_dashboard_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @address = @order.address
    @canceled_or_completed_message = @order.canceled_or_completed
    @user = @order.user
  end

  def index
    @user = User.find(session[:user])
    @orders = @user.orders
  end

  def setup_charge
    # Amount in cents
    @amount = @cart.total_cost
    @amount_string = to_pennies(@amount)

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount_string,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
  end

  def create
    setup_charge
    @user = User.find(session[:user])
    @order = @user.orders.create(status: 0)
    address = Address.find_by(street_address: params[:address])
    @order.address = address

    Order.make_order(@order, session[:cart])
    flash[:success] = "Order was successfully placed"
    redirect_to orders_path
  end

end

app/views/orders/index.html.erb
<h2>All Orders</h2>
<% @orders.each do |order| %>
  <div class="panel penel-default">
    <p>Order from <%= order.created_at %> <%= pluralize(order.count, 'item') %> <%= link_to "See Details", order_path(order) %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h2>Order from <%= @order.created_at %></h2>
<p> <%= @user.first_name %> <%= @user.last_name %></br>
    <%= @address.street_address %></br>
    <% if @address.secondary_address %>
      <%= @address.secondary_address %></br>
    <% end %>
    <%= @address.city %>, <%= @address.state_abbr %></br>
    <%= @address.zip_code %></br>
</p>
<h3>Order status: <%= @order.status %></h3>
<div class="order-info">
  <p>  Status: <%= @order.status %>
  </br>Total Price: <%= @order.total_price.round(2) %></p>
  <p><%= @canceled_or_completed_message %></p>
</div>
<% @order.items.each do |item| %>
  <div class="panel panel-default">
    <%= link_to item.title, item_path(item) %> $<%= item.price.round(2) %>
    x<%= quantity = Item.find_quantity(item, @order) %> = $<%= Item.find_line_subtotal(quantity, item) %>
  </div>
<% end %>