config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  delete '/carts', to: "carts#destroy", as: "carts"
  get '/cart', to: "carts#show", as: "cart"
  patch '/cart' => 'carts#update'
  resources :items, only: [:index, :show, :update]
  resources :carts, only: [:create]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :addresses, only: [:new, :create, :edit, :destroy]
  end
  namespace :admin do
    get '/dashboard', to: "orders#dashboard"
    resources :orders, only: [:edit, :update]
    resources :items, only: [:index, :update, :edit]
    resources :users, only: [:show]
  end
  resources :orders, only: [:index, :show, :create]
  resources :charges, only: [:new, :create]
  get '/dashboard', to: "users#show"
  post '/login', to: "sessions#create"
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"
  get '/:category' => 'categories#index'
  patch '/carts/:id' => 'carts#update'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gryff Outdoor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-findcond navbar-fixed-top">
    <div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
      <a href="/"><%= image_tag "gryffindor_crest", class: "brand" %></a>
    </div>

    
		<div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-left">
        <li class="active" id="shows-loggedin"><%= session[:message] %><span class="sr-only">(current)</span></li>
      </ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><%= link_to "Items", items_path %><span class="sr-only">(current)</span></li>
        <% if current_user %>
          <li class="active"><%= link_to "Dashboard", dashboard_path %><span class="sr-only">(current)</span></li>
        <% elsif current_user %>
          <li class="active"><%= link_to "Profile", admin_dashboard_path %><span class="sr-only">(current)</span></li>
        <% end %>
        <% if @cart.total_items > 0 %>
          <li class="active"><%= link_to "View Cart (#{@cart.total_items})", cart_path %><span class="sr-only">(current)</span></li>
        <% else %>
          <li class="active"><%= link_to "View Cart", cart_path %><span class="sr-only">(current)</span></li>
        <% end %>
        <li class="active"><%= link_to @login_status, @login_path %><span class="sr-only">(current)</span></li>

        
      </ul>
      </div>
		</div>
  </div>
  
</nav>
    <% flash.each do |type, message| %>
        </br></br></br></br><%= content_tag :div, sanitize(message), class: "alert alert-#{type}", class: "flash" %>
    <% end %>

    <%= yield %>
  </body>
</html>